use serde::{Deserialize, Serialize};

use super::settings::ScoringSettings;
// {
//     "name": "Fantasy Football Fetish",
//     "status": "pre_draft",
//     "metadata": {
//       "auto_continue": "on",
//       "copy_from_league_id": "1124894562809384960",
//       "division_1": "Hill City",
//       "division_2": "Flying Lion",
//       "keeper_deadline": "1"
//     },
//     "settings": {
//       "best_ball": 0,
//       "waiver_budget": 100,
//       "disable_adds": 0,
//       "divisions": 2,
//       "capacity_override": 1,
//       "waiver_bid_min": 0,
//       "taxi_deadline": 0,
//       "draft_rounds": 3,
//       "reserve_allow_na": 0,
//       "start_week": 1,
//       "playoff_seed_type": 0,
//       "playoff_teams": 7,
//       "veto_votes_needed": 7,
//       "num_teams": 14,
//       "daily_waivers_hour": 0,
//       "playoff_type": 0,
//       "taxi_slots": 0,
//       "daily_waivers_days": 5461,
//       "playoff_week_start": 15,
//       "waiver_clear_days": 2,
//       "reserve_allow_doubtful": 0,
//       "commissioner_direct_invite": 0,
//       "veto_auto_poll": 1,
//       "reserve_allow_dnr": 0,
//       "taxi_allow_vets": 0,
//       "waiver_day_of_week": 2,
//       "playoff_round_type": 0,
//       "reserve_allow_out": 1,
//       "reserve_allow_sus": 0,
//       "veto_show_votes": 0,
//       "trade_deadline": 11,
//       "taxi_years": 0,
//       "daily_waivers": 0,
//       "disable_trades": 0,
//       "pick_trading": 1,
//       "type": 1,
//       "max_keepers": 1,
//       "waiver_type": 0,
//       "league_average_match": 1,
//       "trade_review_days": 2,
//       "bench_lock": 0,
//       "offseason_adds": 0,
//       "leg": 1,
//       "reserve_slots": 2,
//       "reserve_allow_cov": 0
//     },
//     "avatar": null,
//     "company_id": null,
//     "scoring_settings": {
//       "sack": 1.0,
//       "fgm_40_49": 4.0,
//       "pass_int": -1.0,
//       "pts_allow_0": 10.0,
//       "pass_2pt": 2.0,
//       "st_td": 6.0,
//       "rec_td": 6.0,
//       "idp_blk_kick": 3.0,
//       "fgm_30_39": 3.0,
//       "xpmiss": -1.0,
//       "rush_td": 6.0,
//       "rec_2pt": 2.0,
//       "idp_tkl_loss": 2.0,
//       "idp_tkl_solo": 2.0,
//       "st_fum_rec": 1.0,
//       "fgmiss": -1.0,
//       "ff": 1.0,
//       "idp_int": 6.0,
//       "rec": 1.0,
//       "idp_safe": 3.0,
//       "pts_allow_14_20": 1.0,
//       "fgm_0_19": 3.0,
//       "idp_def_td": 6.0,
//       "int": 2.0,
//       "def_st_fum_rec": 1.0,
//       "fum_lost": -2.0,
//       "pts_allow_1_6": 7.0,
//       "idp_sack": 6.0,
//       "fgm_20_29": 3.0,
//       "pts_allow_21_27": 0.0,
//       "xpm": 1.0,
//       "rush_2pt": 2.0,
//       "fum_rec": 2.0,
//       "idp_pass_def": 3.0,
//       "def_st_td": 6.0,
//       "fgm_50p": 5.0,
//       "def_td": 6.0,
//       "idp_fum_rec": 3.0,
//       "safe": 2.0,
//       "pass_yd": 0.04,
//       "blk_kick": 2.0,
//       "pass_td": 4.0,
//       "idp_qb_hit": 1.0,
//       "rush_yd": 0.1,
//       "fum": 0.0,
//       "pts_allow_28_34": -1.0,
//       "pts_allow_35p": -4.0,
//       "fum_rec_td": 6.0,
//       "rec_yd": 0.1,
//       "def_st_ff": 1.0,
//       "pts_allow_7_13": 4.0,
//       "idp_ff": 3.0,
//       "st_ff": 1.0,
//       "idp_tkl_ast": 1.0
//     },
//     "season": "2024",
//     "season_type": "regular",
//     "shard": 841,
//     "sport": "nfl",
//     "last_message_id": "1129187031353147392",
//     "last_author_avatar": "efed26dac3b993bfb078cb5e7e4480df",
//     "last_author_display_name": "turbowsu",
//     "last_author_id": "991840724020785152",
//     "last_author_is_bot": false,
//     "last_message_attachment": null,
//     "last_message_text_map": null,
//     "last_message_time": 1723581676857,
//     "last_pinned_message_id": "1127851809629913088",
//     "last_read_id": null,
//     "draft_id": "1127404403679559680",
//     "league_id": "1124926301107884032",
//     "previous_league_id": "0",
//     "group_id": null,
//     "bracket_id": null,
//     "loser_bracket_id": null,
//     "roster_positions": [
//       "QB",
//       "RB",
//       "WR",
//       "WR",
//       "TE",
//       "FLEX",
//       "WRRB_FLEX",
//       "K",
//       "DEF",
//       "DL",
//       "BN",
//       "BN",
//       "BN",
//       "BN",
//       "BN"
//     ],
//     "total_rosters": 14
//   }

// #[derive(Debug, Deserialize, Serialize, Clone)]
// pub enum LeagueStatus {
//     PreDraft = "pre_draft",
//     Drafting = "drafting",
//     InSeason = "in_season",
//     Complete = "complete"
// }

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct League {
    pub total_rosters: u32,
    pub status: String,
    pub sport: String,
    pub settings: LeagueSettings,
    pub season_type: String,
    pub season: u32,
    pub scoring_settings: ScoringSettings,
    //pub roster_positions: RosterPostions,
    pub previous_league_id: u128,
    pub name: String,
    pub league_id: String,
    pub draft_id: String,
    pub avatar: String,
    pub company_id: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct LeagueSettings {
    pub best_ball: u32,
    pub waiver_budget: u32,
    pub disable_adds: u32,
    pub divisions: u8,
    pub capacity_override: u16,
    pub waiver_bid_min: u32,
    pub taxi_deadline: u32,
    pub draft_rounds: u8,
    pub reserve_allow_na: u8,
    pub start_week: u16,
    pub playoff_seed_type: u32,
    pub playoff_teams: u16,
    pub veto_votes_needed: u16,
    pub num_teams: u16,
    pub daily_waivers_hour: u16,
    pub playoff_type: u16,
    pub taxi_slots: u16,
    pub daily_waivers_days: u32,
    pub playoff_week_start: u16,
    pub waiver_clear_days: u16,
    pub reserve_allow_doubtful: u16,
    pub commissioner_direct_invite: u16,
    pub veto_auto_poll: u16,
    pub reserve_allow_dnr: u16,
    pub taxi_allow_vets: u16,
    pub waiver_day_of_week: u8,
    pub playoff_round_type: u16,
    pub reserve_allow_out: u16,
    pub reserve_allow_sus: u16,
    pub veto_show_votes: u16,
    pub trade_deadline: u16,
    pub taxi_years: u16,
    pub daily_waivers: u16,
    pub disable_trades: u16,
    pub pick_trading: u16,
    #[serde(rename = "type")]
    pub league_type: u16,
    pub max_keepers: u8,
    pub waiver_type: u8,
    pub league_average_match: u8,
    pub trade_review_days: u8,
    pub bench_lock: u8,
    pub offseason_adds: u8,
    pub leg: u8,
    pub reserve_slots: u8,
    pub reserve_allow_cov: u8,
}
